#!/bin/sh
## Black        0;30     Dark Gray     1;30
## Red          0;31     Light Red     1;31
## Green        0;32     Light Green   1;32
## Brown/Orange 0;33     Yellow        1;33
## Blue         0;34     Light Blue    1;34
## Purple       0;35     Light Purple  1;35
## Cyan         0;36     Light Cyan    1;36
## Light Gray   0;37     White         1;37

color1='\033[1;31m'  # light red
color2='\033[0;31m'  # red
color3='\033[1;32m'  # light green
color4='\033[0;32m'  # green
color5='\033[1;34m'  # light blue
color6='\033[0;34m'  # blue
color7='\033[1;35m'  # light purple
color8='\033[0;35m'  # purple
color9='\033[1;36m'  # light cyan
color10='\033[0;36m'  # cyan
color11='\033[0;37m'  # light grey
color12='\033[1;37m'  # white
color13='\033[0;33m'  # brown
color14='\033[1;33m'  # yellow
color15='\033[0;30m'  # black
color16='\033[1;30m'  # dark gray
nocolor='\033[0m'    # no color

companyname='Dark Web Investments, LLC'
divisionname='Cryptographic Asset Division'
weathercity='Anchorage'
networkad='eth0'

figlet AKcryptoGUY
printf "               ${color1}.-.${nocolor}\n"
printf "         ${color7}.-'\`\`${color1}(   )    ${color5}${companyname}${nocolor}\n"
printf "      ${color14},\`\\ ${color7}\\    ${color1}\`-\`${color7}.    ${color3}${divisionname}${nocolor}\n"
printf "     ${color14}/   \\ ${color7}'\`\`-.   \`   ${color14}System OS: `lsb_release -s -d`${nocolor}\n"
printf "   ${color7}.-.  ${color14},       ${color7}\`___:  ${color14}`uname -srmo`${nocolor}\n"
printf "  ${color7}(   ) ${color14}:       ${color1} ___   ${color14}Hostname: $(hostname) \n"
printf "   ${color7}\`-\`  ${color14}\`      ${color1} ,   :${color13}  Weather (${weathercity}): `curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?locCode=${weathercity}" | sed
-n '/Currently:/ s/.*: \(.*\): \([0-9]*\)\([CF]\).*/\2°\3, \1/p'`\n"
printf "     ${color7}\\   / ${color1},..-\`   ,${color10}   Internal IP: `/sbin/ifconfig ${networkad} | /bin/grep "inet addr" | /usr/bin/cut -d ":" -f 2 | /usr/bin/cut -d " " -f 1`\n"
printf "      ${color7}\`./${color1} /    ${color14}.-.${color1}\`${color10}    External IP: `/usr/bin/wget -q -O - http://icanhazip.com/ | /usr/bin/tail`\n"
printf "         ${color1}\`-..-${color14}(   )${color1}    ** Uptime: `/usr/bin/uptime -p` **${nocolor}\n"
printf "               ${color14}\`-\`${nocolor}     ${nocolor}\n"
# printf "               ${color1}   ${nocolor}\n"
